//
//  LogoView.m
//  YOLayoutExample
//
//  Created by John Boiles on 12/16/14.
//  Copyright (c) 2014 YOLayout. All rights reserved.
//

#import "LogoView.h"

@implementation LogoView

- (void)viewInit {
  [super viewInit];
    self.backgroundColor = [UIColor whiteColor];

    // Size to an aspect ratio of 4.090909091:1
    self.layout = [YOLayout layoutWithLayoutBlock:^CGSize(YOLayout *layout, CGSize size) {
        return CGSizeMake(size.width, ceilf(size.width * 0.244444444));
    }];
}

- (void)drawInRect:(CGRect)rect {
    //// Color Declarations
    UIColor* color1 = [UIColor colorWithRed: 0.916 green: 0.379 blue: 0.228 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.06633 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.01649 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.02496 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.01649 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.07220 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.49612 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.07220 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.10896 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.10896 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.49612 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.15620 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.01649 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.11637 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.01649 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.09084 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.32222 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.09033 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.32222 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.06633 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.01649 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.20267 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41194 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.20356 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.27680 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.20267 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.35877 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.20296 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31372 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.20713 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.18597 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.20416 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23988 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.20535 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.20960 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.21479 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.13446 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.20892 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.16234 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.21148 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.14517 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.22794 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.11840 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.21811 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.12375 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.22250 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.11840 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.24109 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.13446 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.23339 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.11840 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.23777 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.12375 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.24875 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.18597 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.24441 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.14517 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.24696 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.16234 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.25233 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.27680 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.25054 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.20960 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.25173 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23988 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.25322 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41194 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.25292 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31372 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.25322 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.35877 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.25233 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.54763 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.25322 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46511 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.25292 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.51034 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.24875 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.63846 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.25173 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.58492 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.25054 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.61520 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.24109 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.68942 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.24696 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.66172 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.24441 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67871 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.22794 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70548 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.23777 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70012 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.23339 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70548 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.21479 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.68942 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.22250 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70548 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.21811 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70012 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.20713 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.63846 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.21148 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67871 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.20892 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.66172 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.20356 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.54763 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.20535 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.61520 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.20416 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.58492 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.20267 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41194 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.20296 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.51034 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.20267 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46511 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.20267 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41194 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.16590 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41194 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.16782 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.57809 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.16590 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.47249 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.16654 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52788 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.17624 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70769 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.16909 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.62831 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.17190 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67151 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.19501 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.79077 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.18058 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.74388 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.18684 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77157 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.22794 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.20318 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80997 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.21416 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.26088 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.79077 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.24173 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.25271 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80997 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.27965 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70769 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.26905 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77157 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.27530 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.74388 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.28807 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.57809 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.28399 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67151 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.28679 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.62831 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.28999 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41194 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.28935 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52788 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.28999 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.47249 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.28807 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.24634 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.28999 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.35212 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.28935 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.29692 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.27965 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.11618 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.28679 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19575 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.28399 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.15237 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.26088 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.03145 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.27530 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.08000 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.26905 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.05175 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.22794 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.00098 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.25271 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.01114 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.24173 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.00098 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.19501 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.03145 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.21416 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.00098 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.20318 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.01114 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.17624 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.11618 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.18684 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.05175 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.18058 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.08000 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.16782 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.24634 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.17190 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.15237 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.16909 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19575 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.16590 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41194 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.16654 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.29692 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.16590 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.35212 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.16590 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41194 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.62683 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.46965 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.66892 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64308 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.47101 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65711 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.46441 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.69772 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.46828 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.68074 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.46654 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.69034 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.45739 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71378 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.46228 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70511 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.45994 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71046 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.44999 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71877 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.45484 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71711 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.45237 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71877 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.43977 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.69440 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.44522 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71877 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.44182 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71065 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.43671 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.63569 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.43773 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67815 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.43671 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65858 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.44130 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.57255 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.43671 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.60911 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.43824 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.58806 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.45662 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53932 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.44437 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.55705 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.44948 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.54597 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.46403 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52880 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.45884 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53711 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.46130 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53360 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.46675 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52400 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.46930 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.51754 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.40735 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.39422 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.43901 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.39422 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.43901 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.37760 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.44309 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.32111 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.43901 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.35397 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.44037 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.33514 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.45535 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30006 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.44582 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30708 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.44990 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30006 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.46799 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31945 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.46131 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30006 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.46552 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30652 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.37317 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.47045 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.33237 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.35028 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.46862 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41858 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.39311 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.47067 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40825 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.45765 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.44295 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.46658 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.42892 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.46292 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.43705 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.43773 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46622 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.42203 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.49169 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.43160 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.47360 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.42637 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.48209 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.41130 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52769 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.41769 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50129 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.41411 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.51329 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.40505 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.57975 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.40850 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.54209 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.40641 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.55945 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.40301 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65231 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.40369 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.60006 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.40301 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.62425 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.40479 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71268 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.40301 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67225 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.40360 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.69237 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.41041 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76751 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.40599 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.73298 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.40786 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.75126 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.42062 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80572 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.41296 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.78375 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.41637 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.79649 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.43620 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.42488 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81495 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.43007 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.45701 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80572 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.44471 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.45165 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81495 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47118 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.74535 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.46237 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.79649 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.46709 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77637 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47169 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.74535 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47335 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77692 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.47220 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.75569 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.47275 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76622 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.47603 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.47394 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.78763 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.47484 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.79778 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.50973 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.50628 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.75754 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.50803 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.78966 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.50688 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77305 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.50539 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.69218 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.50569 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.74203 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.50539 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.72025 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.50539 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.37871 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.50348 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30505 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.50539 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.35212 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.50475 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.32757 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.49620 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.24689 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.50220 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.28252 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.49977 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.26314 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.48113 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.20923 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.49262 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23065 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.48760 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21809 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.45560 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19594 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.47467 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.20037 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.46616 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19594 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.43684 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.20535 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.44896 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19594 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.44271 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19908 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.42152 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23637 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.43096 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21163 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.42586 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.22197 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.41118 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.29286 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.41718 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.25077 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.41373 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.26960 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.40735 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.37982 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.40862 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31612 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.40735 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.34511 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.40735 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.39422 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.53041 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88492 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.53041 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.99902 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.54471 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.99902 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.56501 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.99126 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.55288 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.99902 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.55965 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.99643 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.57879 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.95858 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.57037 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.98609 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.57496 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.97520 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.58875 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88769 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.58262 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.94197 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.58594 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.91834 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.59756 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76751 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.59156 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.85705 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.59450 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81698 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.63075 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.59552 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.57765 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.62351 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.57713 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.62351 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.55671 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.51994 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.55850 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.55352 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.86609 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.55799 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83175 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.55633 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.85132 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.53960 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88825 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.55071 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88086 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.54607 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88825 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.53041 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88492 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.53654 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88825 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.53348 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88714 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.53041 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.88492 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.67441 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.67492 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.42523 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.67441 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.47914 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.67458 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.45108 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.67735 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.35877 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.67526 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.39938 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.67607 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.37723 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.68309 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31557 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.67862 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.34031 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.68054 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.32591 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.69330 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30006 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.68565 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30523 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.68905 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30006 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.70811 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.34880 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.70045 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30006 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.70539 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31631 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.71220 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.71084 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.38129 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.71220 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.43483 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.70811 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67003 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.71220 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.58400 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.71084 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.63754 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.69330 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71877 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.70539 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70252 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.70045 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71877 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.68309 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70326 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.68905 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71877 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.68565 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71360 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.67735 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.66006 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.68054 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.69292 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.67862 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67852 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.67492 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.59360 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.67607 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64160 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.67526 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.61945 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.67441 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.67458 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.56775 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.67441 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53969 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.67441 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.63918 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.64173 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64622 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.63918 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.56111 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.64003 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.60671 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.65041 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.74480 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.64343 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.68572 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.64633 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71858 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.66701 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80240 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.65450 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77102 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.66003 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.79022 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.69330 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.67399 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81458 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.68275 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.82031 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.71871 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80074 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.70335 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.71182 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81329 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.73543 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.74258 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.72560 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.78818 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.73118 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76880 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.74462 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64455 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.73969 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71637 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.74275 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.68369 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.74743 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.74650 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.60542 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.74743 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.56037 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.74488 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.37206 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.74743 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.45698 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.74658 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41120 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.73620 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.27348 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.74318 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.33292 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.74028 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30006 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.71960 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21422 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.73211 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.24689 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.72658 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.22714 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.69330 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19594 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.71262 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.20129 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.70386 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19520 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.66790 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21643 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.68326 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.19594 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.67479 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.20277 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.65118 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.27625 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.66101 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23009 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.65543 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.25003 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.64199 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.37428 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.64692 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.30246 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.64386 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.33514 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.63918 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.64011 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.41342 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.63918 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.45846 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.63918 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.50942 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.83679 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.73760 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.83679 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.87050 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.87050 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.83526 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.83526 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.60689 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.81662 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70548 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.83526 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67262 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.82905 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70548 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.80513 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.68720 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.81135 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70548 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.80752 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.69938 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.80156 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.62240 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.80275 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67502 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.80156 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65342 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.80156 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.76633 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.76633 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65342 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.77539 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.78135 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.76633 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71323 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.76935 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.75588 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.80130 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.78143 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80683 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.79007 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.82173 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80074 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.80896 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81957 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.81577 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81329 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.83628 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.73760 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.82769 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.78818 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.83254 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76714 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.83679 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.73760 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.90165 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.04086 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.90165 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.88377 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.88377 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31557 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.90165 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31557 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.90165 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65674 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.90292 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.73206 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.90165 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.68702 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.90207 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71212 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.90765 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.78025 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.90377 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.75200 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.90535 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76806 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.91760 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80462 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.90994 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.79243 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.91326 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80055 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.93433 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81071 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.92194 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80868 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.92752 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81071 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.94594 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80905 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.93841 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81071 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.94228 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.81015 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.95730 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.94960 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80794 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.95339 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.80738 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.95730 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70105 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.95348 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70271 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.95611 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70178 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.95484 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70234 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.94939 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70326 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.95211 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70308 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.95075 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70326 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.93930 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.68831 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.94428 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70326 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.94092 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.69828 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.93688 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.63791 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.93769 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.67834 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.93688 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.66154 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.93688 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31557 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.95730 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.31557 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.95730 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.93688 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.21145 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.93688 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.04086 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.90165 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.04086 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.29500 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23887 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.31111 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23887 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.31111 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.82252 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.38104 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.82252 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.31111 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.82252 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.38073 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.82252 * CGRectGetHeight(rect))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.38136 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.87698 * CGRectGetHeight(rect)) controlPoint1: CGPointMake(CGRectGetMinX(rect) + 0.38136 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.82252 * CGRectGetHeight(rect)) controlPoint2: CGPointMake(CGRectGetMinX(rect) + 0.38136 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.87698 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.41960 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76310 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.38136 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64569 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.38136 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70633 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.34379 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70633 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.34379 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23887 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.36216 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23887 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.32646 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.01533 * CGRectGetHeight(rect))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.29500 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.23887 * CGRectGetHeight(rect))];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;
    
    bezierPath.usesEvenOddFillRule = YES;
    
    [color1 setFill];
    [bezierPath fill];
    
    
    //// horizontal-lines-5
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.34615 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.34615 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.34615 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.33846 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.33846 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.33846 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.33846 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.34615 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.34615 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40769 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40769 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40769 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40000 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40000 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40000 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40000 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40769 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.40769 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46923 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46923 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46923 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46154 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46154 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46154 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46154 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46923 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.46923 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53077 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53077 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53077 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52308 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52308 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52308 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.52308 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53077 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.53077 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.59231 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.59231 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.59231 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.58462 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.58462 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.58462 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.58462 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.59231 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.59231 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65385 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65385 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65385 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64615 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64615 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64615 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.64615 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65385 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.65385 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71538 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71538 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71538 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70769 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70769 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70769 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.70769 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71538 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.71538 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77692 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77692 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77692 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76923 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76923 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76923 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.76923 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77692 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.77692 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83846 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83846 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83846 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83077 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83077 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83077 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83077 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83846 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.83846 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.90000 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.90000 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.90000 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99911 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.89231 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.99823 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.89231 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.89231 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.89231 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00089 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.90000 * CGRectGetHeight(rect))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(rect) + 0.00177 * CGRectGetWidth(rect), CGRectGetMinY(rect) + 0.90000 * CGRectGetHeight(rect))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;
        
        bezier2Path.lineCapStyle = kCGLineCapSquare;
        
        bezier2Path.usesEvenOddFillRule = YES;
        
        [color2 setStroke];
        bezier2Path.lineWidth = 0.5;
        [bezier2Path stroke];
    }
}

- (void)drawRect:(CGRect)rect {
    [self drawInRect:CGRectMake(0, 0, self.frame.size.width, self.frame.size.height)];    
}

@end
